// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// ); 
/// ``` 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqa1bE4CRSpKKOmyvFa5j1GMvI-sySaM8',
    appId: '1:232425786136:web:18982768cdcc248cb92c6d',
    messagingSenderId: '232425786136',
    projectId: 'pictranslate-d4da7',
    authDomain: 'pictranslate-d4da7.firebaseapp.com',
    storageBucket: 'pictranslate-d4da7.firebasestorage.app',
    measurementId: 'G-0N1VP6C5SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJhKwE1jBNKjWXzrze8lJmj3s88yYyfcI',
    appId: '1:232425786136:android:5b84c2525fde1863b92c6d',
    messagingSenderId: '232425786136',
    projectId: 'pictranslate-d4da7',
    storageBucket: 'pictranslate-d4da7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxUINJCsDbRYC1E7jWV6YinWSP2DlE1Lc',
    appId: '1:232425786136:ios:892010b8ea928983b92c6d',
    messagingSenderId: '232425786136',
    projectId: 'pictranslate-d4da7',
    storageBucket: 'pictranslate-d4da7.firebasestorage.app',
    iosBundleId: 'com.example.pictranslate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxUINJCsDbRYC1E7jWV6YinWSP2DlE1Lc',
    appId: '1:232425786136:ios:892010b8ea928983b92c6d',
    messagingSenderId: '232425786136',
    projectId: 'pictranslate-d4da7',
    storageBucket: 'pictranslate-d4da7.firebasestorage.app',
    iosBundleId: 'com.example.pictranslate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqa1bE4CRSpKKOmyvFa5j1GMvI-sySaM8',
    appId: '1:232425786136:web:67cc9ce9378a9c6eb92c6d',
    messagingSenderId: '232425786136',
    projectId: 'pictranslate-d4da7',
    authDomain: 'pictranslate-d4da7.firebaseapp.com',
    storageBucket: 'pictranslate-d4da7.firebasestorage.app',
    measurementId: 'G-B8LEML9KC8',
  );
}
